export interface ItemOrcamentoDetalhado {
  id: string;
  poloId: string;
  atividade: string;
  categoria: string;
  item: string;
  descricao: string;
  quantidade: string;
  previsto: number;
  realizado: number;
}

export const itensOrcamentoOFICIAIS: ItemOrcamentoDetalhado[] = [
  // ==========================================
  // POLO PENHA - JIU JITSU (Orçamento: R$ 38.868,27)
  // ==========================================
  {
    id: "penha-jj-1",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Pessoal",
    item: "Professor(a) de Jiu-jitsu",
    descricao: "Responsável pela condução técnica, pedagógica e disciplinar da oficina",
    quantidade: "2 profissional",
    previsto: 7000.00,
    realizado: 0,
  },
  {
    id: "penha-jj-2",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Pessoal",
    item: "Monitor(a) de apoio",
    descricao: "Apoio à turma, organização da aula e acompanhamento dos alunos",
    quantidade: "2 profissional",
    previsto: 2400.00,
    realizado: 0,
  },
  {
    id: "penha-jj-3",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Materiais esportivos",
    item: "Tatame EVA 30mm",
    descricao: "Estrutura de piso para prática da modalidade",
    quantidade: "1 kit com placas para o ciclo",
    previsto: 477.35,
    realizado: 0,
  },
  {
    id: "penha-jj-4",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Materiais esportivos",
    item: "Kimonos infantis / juvenis",
    descricao: "Apoio a alunos em situação de vulnerabilidade e uso institucional",
    quantidade: "80 unidades no ciclo",
    previsto: 2112.14,
    realizado: 0,
  },
  {
    id: "penha-jj-5",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Materiais esportivos",
    item: "Faixas e itens de graduação",
    descricao: "Materiais pedagógicos ligados à progressão técnica dos alunos",
    quantidade: "80 unidades no ciclo",
    previsto: 453.34,
    realizado: 0,
  },
  {
    id: "penha-jj-6",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Materiais / consumo",
    item: "Higienização de tatame e materiais",
    descricao: "Álcool, desinfetante e insumos de limpeza específica",
    quantidade: "1 provisão mensal",
    previsto: 250.00,
    realizado: 0,
  },
  {
    id: "penha-jj-7",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Materiais / consumo",
    item: "Materiais de apoio e primeiros cuidados",
    descricao: "Esparadrapo, gaze, gelo e itens preventivos",
    quantidade: "1 provisão mensal",
    previsto: 180.00,
    realizado: 0,
  },
  {
    id: "penha-jj-8",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Materiais",
    item: "Gráfica / certificados / avaliação",
    descricao: "Certificados, listas, fichas e materiais de apoio",
    quantidade: "1 provisão mensal",
    previsto: 300.00,
    realizado: 0,
  },
  {
    id: "penha-jj-9",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Comunicação",
    item: "Comunicação institucional local",
    descricao: "Divulgação local da oficina e comunicação com a comunidade",
    quantidade: "1 provisão mensal",
    previsto: 450.00,
    realizado: 0,
  },
  {
    id: "penha-jj-10",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Evento pedagógico / esportivo",
    item: "Exame de faixa / culminância semestral",
    descricao: "Provisão para graduação semestral e encerramento simples do ciclo",
    quantidade: "1 provisão mensal",
    previsto: 500.00,
    realizado: 0,
  },
  {
    id: "penha-jj-11",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Encargos",
    item: "INSS patronal",
    descricao: "Contribuição patronal incidente sobre a folha",
    quantidade: "1 provisão mensal",
    previsto: 1400.00,
    realizado: 0,
  },
  {
    id: "penha-jj-12",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Encargos",
    item: "FGTS",
    descricao: "Depósito mensal de FGTS",
    quantidade: "1 provisão mensal",
    previsto: 560.00,
    realizado: 0,
  },
  {
    id: "penha-jj-13",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Encargos",
    item: "PIS sobre folha",
    descricao: "Contribuição sobre a folha de pagamento",
    quantidade: "1 provisão mensal",
    previsto: 70.00,
    realizado: 0,
  },
  {
    id: "penha-jj-14",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Encargos",
    item: "Provisão de 13º salário",
    descricao: "Reserva mensal proporcional para décimo terceiro",
    quantidade: "1 provisão mensal",
    previsto: 583.34,
    realizado: 0,
  },
  {
    id: "penha-jj-15",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Encargos",
    item: "Provisão de férias + 1/3",
    descricao: "Reserva mensal proporcional para férias e adicional constitucional",
    quantidade: "1 provisão mensal",
    previsto: 777.10,
    realizado: 0,
  },
  {
    id: "penha-jj-16",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Encargos",
    item: "Provisão de multa FGTS",
    descricao: "Reserva prudencial para multa rescisória",
    quantidade: "1 provisão mensal",
    previsto: 280.00,
    realizado: 0,
  },
  {
    id: "penha-jj-17",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Infraestrutura",
    item: "Limpeza profissional (rateio)",
    descricao: "Participação da oficina na limpeza dos espaços compartilhados",
    quantidade: "1 rateio mensal",
    previsto: 1000.00,
    realizado: 0,
  },
  {
    id: "penha-jj-18",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Infraestrutura",
    item: "Produtos de limpeza (rateio)",
    descricao: "Participação em materiais de higiene e limpeza",
    quantidade: "1 rateio mensal",
    previsto: 500.00,
    realizado: 0,
  },
  {
    id: "penha-jj-19",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Administrativo / RH essencial",
    item: "Apoio operacional / recepção (rateio)",
    descricao: "Apoio ao fluxo de alunos e organização operacional",
    quantidade: "1 rateio mensal",
    previsto: 450.00,
    realizado: 0,
  },
  {
    id: "penha-jj-20",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Infraestrutura",
    item: "Manutenção leve do espaço (rateio)",
    descricao: "Pequenos reparos e conservação",
    quantidade: "1 rateio mensal",
    previsto: 1000.00,
    realizado: 0,
  },
  {
    id: "penha-jj-21",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Infraestrutura",
    item: "Segurança / controle de acesso (rateio)",
    descricao: "Participação na segurança patrimonial e controle de entrada",
    quantidade: "1 rateio mensal",
    previsto: 850.00,
    realizado: 0,
  },
  {
    id: "penha-jj-22",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Infraestrutura",
    item: "Primeiros socorros / apoio básico (rateio)",
    descricao: "Itens preventivos e suporte básico",
    quantidade: "1 rateio mensal",
    previsto: 300.00,
    realizado: 0,
  },
  {
    id: "penha-jj-23",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Serviços técnicos essenciais",
    item: "Gestor(a) do projeto (rateio compartilhado)",
    descricao: "Gestão central do conjunto de oficinas",
    quantidade: "1 rateio mensal",
    previsto: 1000.00,
    realizado: 0,
  },
  {
    id: "penha-jj-24",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Serviços técnicos essenciais",
    item: "Coordenação pedagógica geral (rateio compartilhado)",
    descricao: "Supervisão metodológica e alinhamento pedagógico",
    quantidade: "1 rateio mensal",
    previsto: 600.00,
    realizado: 0,
  },
  {
    id: "penha-jj-25",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Serviços técnicos essenciais",
    item: "Coordenação operacional / produção (rateio compartilhado)",
    descricao: "Planejamento operacional, cronograma, execução e articulação",
    quantidade: "1 rateio mensal",
    previsto: 1000.00,
    realizado: 0,
  },
  {
    id: "penha-jj-26",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Serviços técnicos essenciais",
    item: "Coordenação administrativa / RH campo (rateio compartilhado)",
    descricao: "Gestão compartilhada de RH, rotinas e suporte administrativo",
    quantidade: "1 rateio mensal",
    previsto: 600.00,
    realizado: 0,
  },
  {
    id: "penha-jj-27",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Serviços técnicos essenciais",
    item: "Financeiro / compras / prestação (rateio compartilhado)",
    descricao: "Controle financeiro, compras, pagamentos e prestação interna",
    quantidade: "1 rateio mensal",
    previsto: 500.00,
    realizado: 0,
  },
  {
    id: "penha-jj-28",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Serviços técnicos essenciais",
    item: "Comunicação institucional / social media (rateio compartilhado)",
    descricao: "Comunicação central, redes e registro institucional",
    quantidade: "1 rateio mensal",
    previsto: 500.00,
    realizado: 0,
  },
  {
    id: "penha-jj-29",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Serviços técnicos essenciais",
    item: "Contábil / fiscal / jurídico (rateio compartilhado)",
    descricao: "Suporte contábil, fiscal e jurídico compartilhado",
    quantidade: "1 rateio mensal",
    previsto: 400.00,
    realizado: 0,
  },
  {
    id: "penha-jj-30",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Serviços técnicos essenciais",
    item: "TI / suporte / dados (rateio compartilhado)",
    descricao: "Suporte técnico, organização de dados e apoio digital",
    quantidade: "1 rateio mensal",
    previsto: 100.00,
    realizado: 0,
  },
  {
    id: "penha-jj-31",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Outros",
    item: "Kit Lanche",
    descricao: "Apoio aos alunos (80 lanches por dia x 2 dias x 4 semanas)",
    quantidade: "80 lanches/dia",
    previsto: 8256.00,
    realizado: 0,
  },
  {
    id: "penha-jj-32",
    poloId: "penha",
    atividade: "Jiu Jitsu",
    categoria: "Extras",
    item: "Custos Extras",
    descricao: "Valor reservado para apoio em imprevistos, competições, transporte",
    quantidade: "1 reserva mensal",
    previsto: 4019.00,
    realizado: 0,
  },

  // ==========================================
  // POLO PENHA - AULA DE INGLÊS (Orçamento: R$ 32.038,20)
  // ==========================================
  {
    id: "penha-ing-1",
    poloId: "penha",
    atividade: "Aula de Inglês",
    categoria: "Pessoal",
    item: "Professor(a) de Inglês",
    descricao: "Responsável pelo planejamento pedagógico, condução das aulas e acompanhamento",
    quantidade: "2 profissionais",
    previsto: 7000.00,
    realizado: 0,
  },
  {
    id: "penha-ing-2",
    poloId: "penha",
    atividade: "Aula de Inglês",
    categoria: "Pessoal",
    item: "Monitor(a) de apoio",
    descricao: "Apoio em sala, controle de presença, organização da turma",
    quantidade: "2 profissionais",
    previsto: 2000.00,
    realizado: 0,
  },
  {
    id: "penha-ing-3",
    poloId: "penha",
    atividade: "Aula de Inglês",
    categoria: "Materiais",
    item: "Material didático",
    descricao: "Apostilas, exercícios e conteúdos de apoio",
    quantidade: "30 kits individuais",
    previsto: 900.00,
    realizado: 0,
  },
  {
    id: "penha-ing-4",
    poloId: "penha",
    atividade: "Aula de Inglês",
    categoria: "Materiais",
    item: "Kit do aluno",
    descricao: "Cadernos, pastas, lápis, canetas e itens básicos",
    quantidade: "30 kits individuais",
    previsto: 600.00,
    realizado: 0,
  },

  // ==========================================
  // POLO MADUREIRA - CORTE E COSTURA (Orçamento: R$ 24.528,37)
  // ==========================================
  {
    id: "mad-cost-1",
    poloId: "madureira",
    atividade: "Corte e Costura",
    categoria: "Pessoal",
    item: "Professora de Corte e Costura",
    descricao: "Responsável pela condução pedagógica da oficina, planejamento e orientação",
    quantidade: "1 profissional",
    previsto: 2500.00,
    realizado: 0,
  },
  {
    id: "mad-cost-2",
    poloId: "madureira",
    atividade: "Corte e Costura",
    categoria: "Pessoal",
    item: "Monitor(a) de apoio",
    descricao: "Apoio à turma, organização do espaço e suporte às atividades",
    quantidade: "1 profissional",
    previsto: 1000.00,
    realizado: 0,
  },
  {
    id: "mad-cost-3",
    poloId: "madureira",
    atividade: "Corte e Costura",
    categoria: "Materiais",
    item: "Máquina de Costura",
    descricao: "Máquinas para substituir antigas",
    quantidade: "6 equipamentos",
    previsto: 1287.08,
    realizado: 0,
  },
  {
    id: "mad-cost-4",
    poloId: "madureira",
    atividade: "Corte e Costura",
    categoria: "Materiais",
    item: "Tecidos",
    descricao: "Tecidos para aulas práticas, exercícios e produção",
    quantidade: "3 kits de 10 metros",
    previsto: 1200.00,
    realizado: 0,
  },

  // ==========================================
  // POLO MADUREIRA - FUTSAL (Orçamento: R$ 26.613,63)
  // ==========================================
  {
    id: "mad-fut-1",
    poloId: "madureira",
    atividade: "Futsal",
    categoria: "Pessoal",
    item: "Professor(a) de Futsal",
    descricao: "Responsável pelo planejamento técnico e condução dos treinos",
    quantidade: "1 profissional",
    previsto: 3400.00,
    realizado: 0,
  },
  {
    id: "mad-fut-2",
    poloId: "madureira",
    atividade: "Futsal",
    categoria: "Pessoal",
    item: "Monitor(a) de apoio",
    descricao: "Apoio à turma, organização da quadra e presença",
    quantidade: "1 profissional",
    previsto: 1000.00,
    realizado: 0,
  },
  {
    id: "mad-fut-3",
    poloId: "madureira",
    atividade: "Futsal",
    categoria: "Materiais esportivos",
    item: "Bolas de futsal",
    descricao: "Aquisição e reposição de bolas para treinos e jogos",
    quantidade: "5 bolas por mês",
    previsto: 674.95,
    realizado: 0,
  },

  // ==========================================
  // POLO MADUREIRA - BASQUETE (Orçamento: R$ 23.159,77)
  // ==========================================
  {
    id: "mad-basq-1",
    poloId: "madureira",
    atividade: "Basquete",
    categoria: "Pessoal",
    item: "Professor(a) de Basquete",
    descricao: "Responsável pelo planejamento técnico e condução dos treinos",
    quantidade: "1 profissional",
    previsto: 3200.00,
    realizado: 0,
  },
  {
    id: "mad-basq-2",
    poloId: "madureira",
    atividade: "Basquete",
    categoria: "Pessoal",
    item: "Monitor(a) de apoio",
    descricao: "Apoio à turma e organização da quadra",
    quantidade: "1 profissional",
    previsto: 1000.00,
    realizado: 0,
  },
];
