/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedGestorRouteRouteImport } from './routes/_authenticated/gestor/route'
import { Route as AuthenticatedGestorIndexRouteImport } from './routes/_authenticated/gestor/index'
import { Route as AuthenticatedGestorAlunosRouteImport } from './routes/_authenticated/gestor/alunos'
import { Route as AuthenticatedGestorAtividadesRouteImport } from './routes/_authenticated/gestor/atividades'
import { Route as AuthenticatedGestorFinanceiroRouteImport } from './routes/_authenticated/gestor/financeiro'
import { Route as AuthenticatedGestorPedidosRouteImport } from './routes/_authenticated/gestor/pedidos'
import { Route as AuthenticatedGestorPolosRouteImport } from './routes/_authenticated/gestor/polos'
import { Route as AuthenticatedGestorProfessoresRouteImport } from './routes/_authenticated/gestor/professores'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGestorRouteRoute =
  AuthenticatedGestorRouteRouteImport.update({
    id: '/gestor',
    path: '/gestor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestorIndexRoute =
  AuthenticatedGestorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)
const AuthenticatedGestorAlunosRoute =
  AuthenticatedGestorAlunosRouteImport.update({
    id: '/alunos',
    path: '/alunos',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)
const AuthenticatedGestorAtividadesRoute =
  AuthenticatedGestorAtividadesRouteImport.update({
    id: '/atividades',
    path: '/atividades',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)
const AuthenticatedGestorFinanceiroRoute =
  AuthenticatedGestorFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)
const AuthenticatedGestorPedidosRoute =
  AuthenticatedGestorPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)
const AuthenticatedGestorPolosRoute =
  AuthenticatedGestorPolosRouteImport.update({
    id: '/polos',
    path: '/polos',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)
const AuthenticatedGestorProfessoresRoute =
  AuthenticatedGestorProfessoresRouteImport.update({
    id: '/professores',
    path: '/professores',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gestor': typeof AuthenticatedGestorRouteRouteWithChildren
  '/gestor/alunos': typeof AuthenticatedGestorAlunosRoute
  '/gestor/atividades': typeof AuthenticatedGestorAtividadesRoute
  '/gestor/financeiro': typeof AuthenticatedGestorFinanceiroRoute
  '/gestor/pedidos': typeof AuthenticatedGestorPedidosRoute
  '/gestor/polos': typeof AuthenticatedGestorPolosRoute
  '/gestor/professores': typeof AuthenticatedGestorProfessoresRoute
  '/gestor/': typeof AuthenticatedGestorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gestor/alunos': typeof AuthenticatedGestorAlunosRoute
  '/gestor/atividades': typeof AuthenticatedGestorAtividadesRoute
  '/gestor/financeiro': typeof AuthenticatedGestorFinanceiroRoute
  '/gestor/pedidos': typeof AuthenticatedGestorPedidosRoute
  '/gestor/polos': typeof AuthenticatedGestorPolosRoute
  '/gestor/professores': typeof AuthenticatedGestorProfessoresRoute
  '/gestor': typeof AuthenticatedGestorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/gestor': typeof AuthenticatedGestorRouteRouteWithChildren
  '/_authenticated/gestor/alunos': typeof AuthenticatedGestorAlunosRoute
  '/_authenticated/gestor/atividades': typeof AuthenticatedGestorAtividadesRoute
  '/_authenticated/gestor/financeiro': typeof AuthenticatedGestorFinanceiroRoute
  '/_authenticated/gestor/pedidos': typeof AuthenticatedGestorPedidosRoute
  '/_authenticated/gestor/polos': typeof AuthenticatedGestorPolosRoute
  '/_authenticated/gestor/professores': typeof AuthenticatedGestorProfessoresRoute
  '/_authenticated/gestor/': typeof AuthenticatedGestorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/gestor'
    | '/gestor/alunos'
    | '/gestor/atividades'
    | '/gestor/financeiro'
    | '/gestor/pedidos'
    | '/gestor/polos'
    | '/gestor/professores'
    | '/gestor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/gestor/alunos'
    | '/gestor/atividades'
    | '/gestor/financeiro'
    | '/gestor/pedidos'
    | '/gestor/polos'
    | '/gestor/professores'
    | '/gestor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/gestor'
    | '/_authenticated/gestor/alunos'
    | '/_authenticated/gestor/atividades'
    | '/_authenticated/gestor/financeiro'
    | '/_authenticated/gestor/pedidos'
    | '/_authenticated/gestor/polos'
    | '/_authenticated/gestor/professores'
    | '/_authenticated/gestor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gestor': {
      id: '/_authenticated/gestor'
      path: '/gestor'
      fullPath: '/gestor'
      preLoaderRoute: typeof AuthenticatedGestorRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestor/': {
      id: '/_authenticated/gestor/'
      path: '/'
      fullPath: '/gestor/'
      preLoaderRoute: typeof AuthenticatedGestorIndexRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
    '/_authenticated/gestor/alunos': {
      id: '/_authenticated/gestor/alunos'
      path: '/alunos'
      fullPath: '/gestor/alunos'
      preLoaderRoute: typeof AuthenticatedGestorAlunosRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
    '/_authenticated/gestor/atividades': {
      id: '/_authenticated/gestor/atividades'
      path: '/atividades'
      fullPath: '/gestor/atividades'
      preLoaderRoute: typeof AuthenticatedGestorAtividadesRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
    '/_authenticated/gestor/financeiro': {
      id: '/_authenticated/gestor/financeiro'
      path: '/financeiro'
      fullPath: '/gestor/financeiro'
      preLoaderRoute: typeof AuthenticatedGestorFinanceiroRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
    '/_authenticated/gestor/pedidos': {
      id: '/_authenticated/gestor/pedidos'
      path: '/pedidos'
      fullPath: '/gestor/pedidos'
      preLoaderRoute: typeof AuthenticatedGestorPedidosRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
    '/_authenticated/gestor/polos': {
      id: '/_authenticated/gestor/polos'
      path: '/polos'
      fullPath: '/gestor/polos'
      preLoaderRoute: typeof AuthenticatedGestorPolosRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
    '/_authenticated/gestor/professores': {
      id: '/_authenticated/gestor/professores'
      path: '/professores'
      fullPath: '/gestor/professores'
      preLoaderRoute: typeof AuthenticatedGestorProfessoresRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
  }
}

interface AuthenticatedGestorRouteRouteChildren {
  AuthenticatedGestorAlunosRoute: typeof AuthenticatedGestorAlunosRoute
  AuthenticatedGestorAtividadesRoute: typeof AuthenticatedGestorAtividadesRoute
  AuthenticatedGestorFinanceiroRoute: typeof AuthenticatedGestorFinanceiroRoute
  AuthenticatedGestorPedidosRoute: typeof AuthenticatedGestorPedidosRoute
  AuthenticatedGestorPolosRoute: typeof AuthenticatedGestorPolosRoute
  AuthenticatedGestorProfessoresRoute: typeof AuthenticatedGestorProfessoresRoute
  AuthenticatedGestorIndexRoute: typeof AuthenticatedGestorIndexRoute
}

const AuthenticatedGestorRouteRouteChildren: AuthenticatedGestorRouteRouteChildren =
  {
    AuthenticatedGestorAlunosRoute: AuthenticatedGestorAlunosRoute,
    AuthenticatedGestorAtividadesRoute: AuthenticatedGestorAtividadesRoute,
    AuthenticatedGestorFinanceiroRoute: AuthenticatedGestorFinanceiroRoute,
    AuthenticatedGestorPedidosRoute: AuthenticatedGestorPedidosRoute,
    AuthenticatedGestorPolosRoute: AuthenticatedGestorPolosRoute,
    AuthenticatedGestorProfessoresRoute: AuthenticatedGestorProfessoresRoute,
    AuthenticatedGestorIndexRoute: AuthenticatedGestorIndexRoute,
  }

const AuthenticatedGestorRouteRouteWithChildren =
  AuthenticatedGestorRouteRoute._addFileChildren(
    AuthenticatedGestorRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGestorRouteRoute: typeof AuthenticatedGestorRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGestorRouteRoute: AuthenticatedGestorRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
