/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedGestorRouteRouteImport } from './routes/_authenticated/gestor/route'
import { Route as AuthenticatedPoloRouteRouteImport } from './routes/_authenticated/polo/route'
import { Route as AuthenticatedGestorIndexRouteImport } from './routes/_authenticated/gestor/index'
import { Route as AuthenticatedGestorAlunosRouteImport } from './routes/_authenticated/gestor/alunos'
import { Route as AuthenticatedGestorAtividadesRouteImport } from './routes/_authenticated/gestor/atividades'
import { Route as AuthenticatedGestorFinanceiroRouteImport } from './routes/_authenticated/gestor/financeiro'
import { Route as AuthenticatedGestorGestoresRouteImport } from './routes/_authenticated/gestor/gestores'
import { Route as AuthenticatedGestorPedidosRouteImport } from './routes/_authenticated/gestor/pedidos'
import { Route as AuthenticatedGestorPolosRouteImport } from './routes/_authenticated/gestor/polos'
import { Route as AuthenticatedGestorProfessoresRouteImport } from './routes/_authenticated/gestor/professores'
import { Route as AuthenticatedPoloIndexRouteImport } from './routes/_authenticated/polo/index'
import { Route as AuthenticatedPoloAlunosRouteImport } from './routes/_authenticated/polo/alunos'
import { Route as AuthenticatedPoloAtividadesRouteImport } from './routes/_authenticated/polo/atividades'
import { Route as AuthenticatedPoloChamadaRouteImport } from './routes/_authenticated/polo/chamada'
import { Route as AuthenticatedPoloComprasRouteImport } from './routes/_authenticated/polo/compras'
import { Route as AuthenticatedPoloGaleriaRouteImport } from './routes/_authenticated/polo/galeria'
import { Route as AuthenticatedPoloPerfilRouteImport } from './routes/_authenticated/polo/perfil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGestorRouteRoute =
  AuthenticatedGestorRouteRouteImport.update({
    id: '/gestor',
    path: '/gestor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPoloRouteRoute = AuthenticatedPoloRouteRouteImport.update({
  id: '/polo',
  path: '/polo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGestorIndexRoute =
  AuthenticatedGestorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)
const AuthenticatedGestorAlunosRoute =
  AuthenticatedGestorAlunosRouteImport.update({
    id: '/alunos',
    path: '/alunos',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)
const AuthenticatedGestorAtividadesRoute =
  AuthenticatedGestorAtividadesRouteImport.update({
    id: '/atividades',
    path: '/atividades',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)
const AuthenticatedGestorFinanceiroRoute =
  AuthenticatedGestorFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)
const AuthenticatedGestorGestoresRoute =
  AuthenticatedGestorGestoresRouteImport.update({
    id: '/gestores',
    path: '/gestores',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)
const AuthenticatedGestorPedidosRoute =
  AuthenticatedGestorPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)
const AuthenticatedGestorPolosRoute =
  AuthenticatedGestorPolosRouteImport.update({
    id: '/polos',
    path: '/polos',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)
const AuthenticatedGestorProfessoresRoute =
  AuthenticatedGestorProfessoresRouteImport.update({
    id: '/professores',
    path: '/professores',
    getParentRoute: () => AuthenticatedGestorRouteRoute,
  } as any)
const AuthenticatedPoloIndexRoute = AuthenticatedPoloIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPoloRouteRoute,
} as any)
const AuthenticatedPoloAlunosRoute = AuthenticatedPoloAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AuthenticatedPoloRouteRoute,
} as any)
const AuthenticatedPoloAtividadesRoute =
  AuthenticatedPoloAtividadesRouteImport.update({
    id: '/atividades',
    path: '/atividades',
    getParentRoute: () => AuthenticatedPoloRouteRoute,
  } as any)
const AuthenticatedPoloChamadaRoute =
  AuthenticatedPoloChamadaRouteImport.update({
    id: '/chamada',
    path: '/chamada',
    getParentRoute: () => AuthenticatedPoloRouteRoute,
  } as any)
const AuthenticatedPoloComprasRoute =
  AuthenticatedPoloComprasRouteImport.update({
    id: '/compras',
    path: '/compras',
    getParentRoute: () => AuthenticatedPoloRouteRoute,
  } as any)
const AuthenticatedPoloGaleriaRoute =
  AuthenticatedPoloGaleriaRouteImport.update({
    id: '/galeria',
    path: '/galeria',
    getParentRoute: () => AuthenticatedPoloRouteRoute,
  } as any)
const AuthenticatedPoloPerfilRoute = AuthenticatedPoloPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedPoloRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gestor': typeof AuthenticatedGestorRouteRouteWithChildren
  '/polo': typeof AuthenticatedPoloRouteRouteWithChildren
  '/gestor/alunos': typeof AuthenticatedGestorAlunosRoute
  '/gestor/atividades': typeof AuthenticatedGestorAtividadesRoute
  '/gestor/financeiro': typeof AuthenticatedGestorFinanceiroRoute
  '/gestor/gestores': typeof AuthenticatedGestorGestoresRoute
  '/gestor/pedidos': typeof AuthenticatedGestorPedidosRoute
  '/gestor/polos': typeof AuthenticatedGestorPolosRoute
  '/gestor/professores': typeof AuthenticatedGestorProfessoresRoute
  '/polo/alunos': typeof AuthenticatedPoloAlunosRoute
  '/polo/atividades': typeof AuthenticatedPoloAtividadesRoute
  '/polo/chamada': typeof AuthenticatedPoloChamadaRoute
  '/polo/compras': typeof AuthenticatedPoloComprasRoute
  '/polo/galeria': typeof AuthenticatedPoloGaleriaRoute
  '/polo/perfil': typeof AuthenticatedPoloPerfilRoute
  '/gestor/': typeof AuthenticatedGestorIndexRoute
  '/polo/': typeof AuthenticatedPoloIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gestor/alunos': typeof AuthenticatedGestorAlunosRoute
  '/gestor/atividades': typeof AuthenticatedGestorAtividadesRoute
  '/gestor/financeiro': typeof AuthenticatedGestorFinanceiroRoute
  '/gestor/gestores': typeof AuthenticatedGestorGestoresRoute
  '/gestor/pedidos': typeof AuthenticatedGestorPedidosRoute
  '/gestor/polos': typeof AuthenticatedGestorPolosRoute
  '/gestor/professores': typeof AuthenticatedGestorProfessoresRoute
  '/polo/alunos': typeof AuthenticatedPoloAlunosRoute
  '/polo/atividades': typeof AuthenticatedPoloAtividadesRoute
  '/polo/chamada': typeof AuthenticatedPoloChamadaRoute
  '/polo/compras': typeof AuthenticatedPoloComprasRoute
  '/polo/galeria': typeof AuthenticatedPoloGaleriaRoute
  '/polo/perfil': typeof AuthenticatedPoloPerfilRoute
  '/gestor': typeof AuthenticatedGestorIndexRoute
  '/polo': typeof AuthenticatedPoloIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/gestor': typeof AuthenticatedGestorRouteRouteWithChildren
  '/_authenticated/polo': typeof AuthenticatedPoloRouteRouteWithChildren
  '/_authenticated/gestor/alunos': typeof AuthenticatedGestorAlunosRoute
  '/_authenticated/gestor/atividades': typeof AuthenticatedGestorAtividadesRoute
  '/_authenticated/gestor/financeiro': typeof AuthenticatedGestorFinanceiroRoute
  '/_authenticated/gestor/gestores': typeof AuthenticatedGestorGestoresRoute
  '/_authenticated/gestor/pedidos': typeof AuthenticatedGestorPedidosRoute
  '/_authenticated/gestor/polos': typeof AuthenticatedGestorPolosRoute
  '/_authenticated/gestor/professores': typeof AuthenticatedGestorProfessoresRoute
  '/_authenticated/polo/alunos': typeof AuthenticatedPoloAlunosRoute
  '/_authenticated/polo/atividades': typeof AuthenticatedPoloAtividadesRoute
  '/_authenticated/polo/chamada': typeof AuthenticatedPoloChamadaRoute
  '/_authenticated/polo/compras': typeof AuthenticatedPoloComprasRoute
  '/_authenticated/polo/galeria': typeof AuthenticatedPoloGaleriaRoute
  '/_authenticated/polo/perfil': typeof AuthenticatedPoloPerfilRoute
  '/_authenticated/gestor/': typeof AuthenticatedGestorIndexRoute
  '/_authenticated/polo/': typeof AuthenticatedPoloIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/gestor'
    | '/polo'
    | '/gestor/alunos'
    | '/gestor/atividades'
    | '/gestor/financeiro'
    | '/gestor/gestores'
    | '/gestor/pedidos'
    | '/gestor/polos'
    | '/gestor/professores'
    | '/polo/alunos'
    | '/polo/atividades'
    | '/polo/chamada'
    | '/polo/compras'
    | '/polo/galeria'
    | '/polo/perfil'
    | '/gestor/'
    | '/polo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/gestor/alunos'
    | '/gestor/atividades'
    | '/gestor/financeiro'
    | '/gestor/gestores'
    | '/gestor/pedidos'
    | '/gestor/polos'
    | '/gestor/professores'
    | '/polo/alunos'
    | '/polo/atividades'
    | '/polo/chamada'
    | '/polo/compras'
    | '/polo/galeria'
    | '/polo/perfil'
    | '/gestor'
    | '/polo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/gestor'
    | '/_authenticated/polo'
    | '/_authenticated/gestor/alunos'
    | '/_authenticated/gestor/atividades'
    | '/_authenticated/gestor/financeiro'
    | '/_authenticated/gestor/gestores'
    | '/_authenticated/gestor/pedidos'
    | '/_authenticated/gestor/polos'
    | '/_authenticated/gestor/professores'
    | '/_authenticated/polo/alunos'
    | '/_authenticated/polo/atividades'
    | '/_authenticated/polo/chamada'
    | '/_authenticated/polo/compras'
    | '/_authenticated/polo/galeria'
    | '/_authenticated/polo/perfil'
    | '/_authenticated/gestor/'
    | '/_authenticated/polo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gestor': {
      id: '/_authenticated/gestor'
      path: '/gestor'
      fullPath: '/gestor'
      preLoaderRoute: typeof AuthenticatedGestorRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/polo': {
      id: '/_authenticated/polo'
      path: '/polo'
      fullPath: '/polo'
      preLoaderRoute: typeof AuthenticatedPoloRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestor/': {
      id: '/_authenticated/gestor/'
      path: '/'
      fullPath: '/gestor/'
      preLoaderRoute: typeof AuthenticatedGestorIndexRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
    '/_authenticated/gestor/alunos': {
      id: '/_authenticated/gestor/alunos'
      path: '/alunos'
      fullPath: '/gestor/alunos'
      preLoaderRoute: typeof AuthenticatedGestorAlunosRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
    '/_authenticated/gestor/atividades': {
      id: '/_authenticated/gestor/atividades'
      path: '/atividades'
      fullPath: '/gestor/atividades'
      preLoaderRoute: typeof AuthenticatedGestorAtividadesRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
    '/_authenticated/gestor/financeiro': {
      id: '/_authenticated/gestor/financeiro'
      path: '/financeiro'
      fullPath: '/gestor/financeiro'
      preLoaderRoute: typeof AuthenticatedGestorFinanceiroRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
    '/_authenticated/gestor/gestores': {
      id: '/_authenticated/gestor/gestores'
      path: '/gestores'
      fullPath: '/gestor/gestores'
      preLoaderRoute: typeof AuthenticatedGestorGestoresRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
    '/_authenticated/gestor/pedidos': {
      id: '/_authenticated/gestor/pedidos'
      path: '/pedidos'
      fullPath: '/gestor/pedidos'
      preLoaderRoute: typeof AuthenticatedGestorPedidosRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
    '/_authenticated/gestor/polos': {
      id: '/_authenticated/gestor/polos'
      path: '/polos'
      fullPath: '/gestor/polos'
      preLoaderRoute: typeof AuthenticatedGestorPolosRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
    '/_authenticated/gestor/professores': {
      id: '/_authenticated/gestor/professores'
      path: '/professores'
      fullPath: '/gestor/professores'
      preLoaderRoute: typeof AuthenticatedGestorProfessoresRouteImport
      parentRoute: typeof AuthenticatedGestorRouteRoute
    }
    '/_authenticated/polo/': {
      id: '/_authenticated/polo/'
      path: '/'
      fullPath: '/polo/'
      preLoaderRoute: typeof AuthenticatedPoloIndexRouteImport
      parentRoute: typeof AuthenticatedPoloRouteRoute
    }
    '/_authenticated/polo/alunos': {
      id: '/_authenticated/polo/alunos'
      path: '/alunos'
      fullPath: '/polo/alunos'
      preLoaderRoute: typeof AuthenticatedPoloAlunosRouteImport
      parentRoute: typeof AuthenticatedPoloRouteRoute
    }
    '/_authenticated/polo/atividades': {
      id: '/_authenticated/polo/atividades'
      path: '/atividades'
      fullPath: '/polo/atividades'
      preLoaderRoute: typeof AuthenticatedPoloAtividadesRouteImport
      parentRoute: typeof AuthenticatedPoloRouteRoute
    }
    '/_authenticated/polo/chamada': {
      id: '/_authenticated/polo/chamada'
      path: '/chamada'
      fullPath: '/polo/chamada'
      preLoaderRoute: typeof AuthenticatedPoloChamadaRouteImport
      parentRoute: typeof AuthenticatedPoloRouteRoute
    }
    '/_authenticated/polo/compras': {
      id: '/_authenticated/polo/compras'
      path: '/compras'
      fullPath: '/polo/compras'
      preLoaderRoute: typeof AuthenticatedPoloComprasRouteImport
      parentRoute: typeof AuthenticatedPoloRouteRoute
    }
    '/_authenticated/polo/galeria': {
      id: '/_authenticated/polo/galeria'
      path: '/galeria'
      fullPath: '/polo/galeria'
      preLoaderRoute: typeof AuthenticatedPoloGaleriaRouteImport
      parentRoute: typeof AuthenticatedPoloRouteRoute
    }
    '/_authenticated/polo/perfil': {
      id: '/_authenticated/polo/perfil'
      path: '/perfil'
      fullPath: '/polo/perfil'
      preLoaderRoute: typeof AuthenticatedPoloPerfilRouteImport
      parentRoute: typeof AuthenticatedPoloRouteRoute
    }
  }
}

interface AuthenticatedGestorRouteRouteChildren {
  AuthenticatedGestorAlunosRoute: typeof AuthenticatedGestorAlunosRoute
  AuthenticatedGestorAtividadesRoute: typeof AuthenticatedGestorAtividadesRoute
  AuthenticatedGestorFinanceiroRoute: typeof AuthenticatedGestorFinanceiroRoute
  AuthenticatedGestorGestoresRoute: typeof AuthenticatedGestorGestoresRoute
  AuthenticatedGestorPedidosRoute: typeof AuthenticatedGestorPedidosRoute
  AuthenticatedGestorPolosRoute: typeof AuthenticatedGestorPolosRoute
  AuthenticatedGestorProfessoresRoute: typeof AuthenticatedGestorProfessoresRoute
  AuthenticatedGestorIndexRoute: typeof AuthenticatedGestorIndexRoute
}

const AuthenticatedGestorRouteRouteChildren: AuthenticatedGestorRouteRouteChildren =
  {
    AuthenticatedGestorAlunosRoute: AuthenticatedGestorAlunosRoute,
    AuthenticatedGestorAtividadesRoute: AuthenticatedGestorAtividadesRoute,
    AuthenticatedGestorFinanceiroRoute: AuthenticatedGestorFinanceiroRoute,
    AuthenticatedGestorGestoresRoute: AuthenticatedGestorGestoresRoute,
    AuthenticatedGestorPedidosRoute: AuthenticatedGestorPedidosRoute,
    AuthenticatedGestorPolosRoute: AuthenticatedGestorPolosRoute,
    AuthenticatedGestorProfessoresRoute: AuthenticatedGestorProfessoresRoute,
    AuthenticatedGestorIndexRoute: AuthenticatedGestorIndexRoute,
  }

const AuthenticatedGestorRouteRouteWithChildren =
  AuthenticatedGestorRouteRoute._addFileChildren(
    AuthenticatedGestorRouteRouteChildren,
  )

interface AuthenticatedPoloRouteRouteChildren {
  AuthenticatedPoloAlunosRoute: typeof AuthenticatedPoloAlunosRoute
  AuthenticatedPoloAtividadesRoute: typeof AuthenticatedPoloAtividadesRoute
  AuthenticatedPoloChamadaRoute: typeof AuthenticatedPoloChamadaRoute
  AuthenticatedPoloComprasRoute: typeof AuthenticatedPoloComprasRoute
  AuthenticatedPoloGaleriaRoute: typeof AuthenticatedPoloGaleriaRoute
  AuthenticatedPoloPerfilRoute: typeof AuthenticatedPoloPerfilRoute
  AuthenticatedPoloIndexRoute: typeof AuthenticatedPoloIndexRoute
}

const AuthenticatedPoloRouteRouteChildren: AuthenticatedPoloRouteRouteChildren =
  {
    AuthenticatedPoloAlunosRoute: AuthenticatedPoloAlunosRoute,
    AuthenticatedPoloAtividadesRoute: AuthenticatedPoloAtividadesRoute,
    AuthenticatedPoloChamadaRoute: AuthenticatedPoloChamadaRoute,
    AuthenticatedPoloComprasRoute: AuthenticatedPoloComprasRoute,
    AuthenticatedPoloGaleriaRoute: AuthenticatedPoloGaleriaRoute,
    AuthenticatedPoloPerfilRoute: AuthenticatedPoloPerfilRoute,
    AuthenticatedPoloIndexRoute: AuthenticatedPoloIndexRoute,
  }

const AuthenticatedPoloRouteRouteWithChildren =
  AuthenticatedPoloRouteRoute._addFileChildren(
    AuthenticatedPoloRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGestorRouteRoute: typeof AuthenticatedGestorRouteRouteWithChildren
  AuthenticatedPoloRouteRoute: typeof AuthenticatedPoloRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGestorRouteRoute: AuthenticatedGestorRouteRouteWithChildren,
  AuthenticatedPoloRouteRoute: AuthenticatedPoloRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
